variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'subsidiaryupload'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'subsidiaryuploadrepository'
  serviceName: '' # need to update
